# Generated by Django 5.0.6 on 2024-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_remove_customer_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='shop/images/album_covers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
